### PR TITLE
update version number so step can be published

### PR DESCRIPTION
**Pull request by dldnh**
A couple of changes have been made recently to this step without being published. They are both backward-compatible bug fixes, I've bumped the patch version number. Publish to staging has been completed, and the step manually tested there.

### CODE REVIEW

**Comment by dldnh** [comment]
Obviously I won't merge this until I fix the problem that broke staging. I'll use this branch for that fix.

**Comment by dldnh** [comment]
I tested the latest manually against web and another local app.

@gsserge Should I publish this to stage so we can make sure all's well the next time web (etc) build?

**Comment by dldnh** [comment]
@gsserge Please let me know on Monday if it's OK to merge this and publish to production

**Comment by gilbode** [comment]
@dindh Guillaume’s last day was last week better ask someone else to review

**Comment by hatchan** [comment]
(@gsserge is Sergey, not Guillaume)

**Comment by hatchan** [comment]
The title and description just mention a version bump, but I also see some code changes. Is this expected?

**Comment by dldnh** [comment]
@hatchan Yes - the original intent was to publish a couple recent changes that hadn't been published, but that broke some stuff, which I fixed.

**Pull request merged**
